// ARCHIVO GENERADO por server/build-sim.mjs a partir de index.html (cartas de jugadores). No editar.
const P=(id,nick,name,pos,rar,st,estilo,fuerte,debil,look,trait)=>({id,nick,name,pos,rar,st,estilo,fuerte,debil,look,trait});
const PLAYERS=[
P('toro','El Toro','Minotauro','MED','comun',{vel:52,tir:74,pas:50,reg:55,def:38,fis:86},'Delantero de choque, gana todo cuerpo a cuerpo.','Físico y tiro potente','Lento y poco regate',{skin:1,hair:'#2b1a10',style:'corto'}),
P('rayo','Rayo','Medina','DEL','rara',{vel:95,tir:62,pas:58,reg:78,def:30,fis:48},'Se escapa de todos en velocidad pura.','Velocidad y regate','Tiro flojo, se cae fácil',{skin:0,hair:'#e2c25a',style:'picos'}),
P('canon','Cañón','Ibarra','DEL','epica',{vel:66,tir:93,pas:52,reg:64,def:35,fis:75},'Dispara de donde sea y casi siempre a puerta.','Tiro de larga distancia','Pase impreciso',{skin:2,hair:'#111111',style:'rapado'}),
P('mago','El Mago','Quintero','DEL','legendaria',{vel:82,tir:84,pas:90,reg:95,def:32,fis:50},'Esquiva barridas como si nada y la pone donde quiere.','Regate, pase y tiro','Físico débil',{skin:1,hair:'#5a3a1a',style:'largo'}),
P('zurdo','Zurdo','Salas','DEL','comun',{vel:68,tir:68,pas:62,reg:66,def:40,fis:62},'Atacante equilibrado, sirve para todo.','Balanceado','No destaca en nada',{skin:0,hair:'#3a2414',style:'corto'}),
P('halcon','Halcón','Robles','DEL','rara',{vel:70,tir:76,pas:55,reg:58,def:45,fis:80},'Rey del cabezazo: alcanza centros que nadie más.','Remate aéreo y físico','Regate limitado',{skin:2,hair:'#111111',style:'afro'},'aereo'),
P('motor','Motor','Castañeda','MED','comun',{vel:72,tir:55,pas:66,reg:60,def:64,fis:74},'Corre los tres minutos sin cansarse.','Presión y resistencia','Poca técnica de tiro',{skin:1,hair:'#2b1a10',style:'cresta'}),
P('pincel','Pincel','Durán','MED','rara',{vel:64,tir:62,pas:92,reg:80,def:48,fis:52},'Pases al pie milimétricos.','Pase perfecto','Defensa y físico',{skin:0,hair:'#8a5a2a',style:'largo'}),
P('tanque','Tanque','Villalobos','MED','epica',{vel:58,tir:60,pas:70,reg:55,def:86,fis:90},'Muro del mediocampo, roba y reparte.','Robo y cuerpo','Lento',{skin:2,hair:'#111111',style:'calvo'}),
P('chispa','Chispa','Ortega','MED','comun',{vel:86,tir:58,pas:56,reg:72,def:44,fis:46},'Eléctrico y desordenado.','Velocidad','Impreciso',{skin:0,hair:'#d94a1a',style:'picos'}),
P('profe','El Profe','Lozano','MED','legendaria',{vel:70,tir:88,pas:94,reg:86,def:62,fis:66},'Lee el juego y carga el súper tiro más rápido que nadie.','Visión y súper tiro rápido','Velocidad media',{skin:1,hair:'#a9a9a9',style:'corto'},'carga'),
P('muro','Muro','Gallardo','DEF','comun',{vel:50,tir:40,pas:52,reg:42,def:80,fis:82},'Barridas fuertes, no deja pasar a nadie.','Barrida y físico','Muy lento',{skin:1,hair:'#2b1a10',style:'rapado'}),
P('ancla','Ancla','Fuentes','DEF','rara',{vel:62,tir:45,pas:70,reg:55,def:84,fis:72},'Siempre bien parado, corta pases.','Marca y pase de salida','Poco tiro',{skin:0,hair:'#5a3a1a',style:'corto'}),
P('martillo','Martillo','Rangel','DEF','epica',{vel:60,tir:50,pas:50,reg:45,def:88,fis:95},'Su choque manda rivales contra la reja.','Cuerpo devastador','Pase y regate',{skin:2,hair:'#111111',style:'cresta'}),
P('flecha','Flecha','Pineda','DEF','comun',{vel:88,tir:48,pas:64,reg:66,def:70,fis:55},'Lateral que sube y baja sin parar.','Velocidad para cerrar','Pierde choques',{skin:0,hair:'#e2c25a',style:'corto'}),
P('capitan','Capitán','Herrera','DEF','legendaria',{vel:76,tir:66,pas:80,reg:70,def:95,fis:88},'Líder total de la defensa.','Defensa completa','Tiro discreto',{skin:1,hair:'#3a2414',style:'largo'}),
P('zurdito','Zurdito','Pequeño hechicero','DEL','legendaria',{vel:85,tir:90,pas:88,reg:96,def:35,fis:55},'Pequeño hechicero zurdo: su bota dorada pone el balón donde quiere.','Regate, zurda mágica y visión','Físico y juego aéreo',{skin:0,hair:'#3a2414',style:'corto'}),
P('cazador','Cazador Polaco','Cazador del bosque','DEL','comun',{vel:66,tir:80,pas:60,reg:64,def:40,fis:72},'Aparece donde cae el balón y no perdona dentro del área.','Definición','Velocidad',{skin:0,hair:'#8a6a4a',style:'corto'}),
P('perro','Perro de Presa','Hombre lobo','MED','comun',{vel:70,tir:55,pas:62,reg:58,def:80,fis:82},'Muerde tobillos los tres minutos y no suelta al rival.','Barrida y presión','Técnica',{skin:1,hair:'#6b6b6b',style:'picos'}),
P('sangre','Sangre Caliente','Demonio de fuego','DEF','comun',{vel:64,tir:45,pas:52,reg:48,def:82,fis:86},'Choca con todo lo que se mueve; mándalo contra la reja.','Cuerpo devastador','Disciplina',{skin:2,hair:'#ff6a1a',style:'picos'}),
P('coletazo','Coletazo','Hombre escorpión','POR','comun',{vel:72,ref:76,alc:70,sal:82,pas:70,fis:60},'Portero loco: sale a jugar y hace atajadas imposibles.','Salidas y atajadas espectaculares','Imprudente',{skin:1,hair:'#2b1a10',style:'afro'}),
P('pausa','La Pausa','Tortuga sabia','MED','rara',{vel:52,tir:68,pas:92,reg:84,def:60,fis:70},'Pisa el balón, levanta la cabeza y pone el pase perfecto.','Pase y control','Velocidad',{skin:0,hair:'#5a8a2a',style:'calvo'}),
P('gigante','Gigante Belga','Troll de montaña','POR','rara',{vel:50,ref:74,alc:94,sal:70,pas:66,fis:90},'Tan grande que tapa casi toda la portería.','Alcance enorme','Reacción lenta abajo',{skin:1,hair:'#6a7a5a',style:'rapado'}),
P('rey','Rey del Nilo','Faraón','DEL','rara',{vel:84,tir:82,pas:70,reg:82,def:38,fis:62},'Sereno y letal: aparece por la banda y define cruzado.','Velocidad y definición','Juego aéreo',{skin:2,hair:'#111111',style:'corto'}),
P('expreso','Expreso Lateral','Hombre guepardo','DEF','comun',{vel:94,tir:52,pas:68,reg:66,def:70,fis:60},'Sube y baja la banda sin cansarse; el más rápido del campo.','Velocidad pura','Choque',{skin:1,hair:'#d9a830',style:'corto'}),
P('gato','El Gato','Hombre gato','POR','comun',{vel:60,ref:76,alc:64,sal:60,pas:55,fis:62},'Reflejos rápidos bajo los palos.','Reflejos','Poco alcance',{skin:1,hair:'#2b1a10',style:'corto'}),
P('pulpo','Pulpo','Cervantes','POR','rara',{vel:52,ref:74,alc:90,sal:62,pas:58,fis:70},'Brazos larguísimos, llega a las esquinas.','Alcance','Lento en salidas',{skin:0,hair:'#5a3a1a',style:'corto'}),
P('arana','Araña','Montes','POR','epica',{vel:70,ref:86,alc:78,sal:88,pas:66,fis:64},'Sale a achicar y cierra el ángulo.','Salidas y reflejos','Físico normal',{skin:2,hair:'#111111',style:'rapado'}),
P('muralla','Muralla Naranja','Gólem de piedra','DEF','legendaria',{vel:62,tir:55,pas:72,reg:55,def:96,fis:95},'Un muro de roca: nadie pasa por su lado.','Defensa y físico','Velocidad',{skin:1,hair:'#7a7a7a',style:'calvo'}),
P('vikingo','Vikingo','Guerrero del norte','DEF','rara',{vel:60,tir:55,pas:58,reg:48,def:86,fis:92},'Defiende su área como un fuerte del norte.','Choque y juego aéreo','Lento al girar',{skin:0,hair:'#c0502a',style:'corto'}),
P('ciclon','Ciclón','Espíritu del viento','DEF','epica',{vel:92,tir:58,pas:74,reg:80,def:74,fis:52},'Sube por la banda como un remolino y vuelve antes que nadie.','Velocidad y recuperación','Físico',{skin:0,hair:'#8fd0ff',style:'picos'}),
P('malabares','Malabares','Hechicero de la samba','MED','legendaria',{vel:82,tir:80,pas:90,reg:97,def:38,fis:58},'Juega sonriendo: lujos, caños y pases sin mirar.','Regate y lujo','Defensa',{skin:2,hair:'#1a1a1a',style:'afro'}),
P('ruleta','Ruleta','Maestro del giro','MED','epica',{vel:66,tir:78,pas:90,reg:90,def:55,fis:72},'Gira sobre el balón y deja a dos rivales en el camino.','Control y pase','Velocidad',{skin:0,hair:'#c9a46a',style:'calvo'}),
P('leon','León Sueco','Rey león','DEL','epica',{vel:70,tir:90,pas:66,reg:78,def:38,fis:88},'Acrobático y arrogante: remata de cualquier forma.','Remate acrobático y físico','Velocidad',{skin:1,hair:'#c98a2a',style:'picos'}),
P('turbo','Turbo Francés','Velocista','DEL','legendaria',{vel:97,tir:86,pas:68,reg:86,def:32,fis:64},'Arranca y ya nadie lo alcanza.','Velocidad y definición','Juego aéreo',{skin:2,hair:'#111111',style:'rapado'}),
];
export const PBY = Object.fromEntries(PLAYERS.map(p => [p.id, p]));
